config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  get "up" => "rails/health#show", as: :rails_health_check
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :content, presence: true
  validates :post, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :body, presence: true
  validates :published_at, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.paginate(page: params[:page], per_page: 10)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :published_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to "App", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Crear cuenta", new_user_registration_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
  <h1 class="mt-5">Lista de Posts</h1>

  <div class="row mt-4">
    <% @posts.each do |post| %>
      <div class="col-md-6">
        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title"><%= post.title %></h2>
            <p class="card-text"><strong>Fecha de Publicación:</strong> <%= post.published_at.strftime("%d/%m/%Y %H:%M") %></p>
            <p class="card-text"><strong>Cuerpo:</strong> <%= post.body %></p> <!-- Agrega esta línea para mostrar el cuerpo del post -->
            <%= link_to "Ver Detalles", post_path(post), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="mt-5">Crear Nuevo Post</h1>

  <div class="row mt-4">
    <div class="col-md-6">
      <%= form_with(model: @post, url: posts_path, method: "post") do |form| %>
        <div class="mb-3">
          <%= form.label :title, class: "form-label" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :body, class: "form-label" %>
          <%= form.text_area :body, class: "form-control", rows: 6 %>
        </div>
        <div class="mb-3">
          <%= form.label :published_at, class: "form-label" %>
          <%= form.datetime_local_field :published_at, class: "form-control" %>
        </div>
        <%= form.submit "Crear Post", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>